name: CI

on:
  - push
    
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    #- uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - name: npm install
        # Install project
      run: make install
      
       #with:
        #node-version: ${{ matrix.node-version }}

    # Runs a single command using the runners shell
    - name: run lint
      run: make lint

    
